name = "lyon-jarrive"
compatibility_date = "2025-08-11"
pages_build_output_dir = "."

[[d1_databases]]
binding = "DB"
database_name = "lyon-jarrive-db"
database_id = "ab638b18-3ab4-4ca8-9ab0-7ec83394b56a"

[env.production]
d1_databases = [
  { binding = "DB", database_name = "lyon-jarrive-db", database_id = "ab638b18-3ab4-4ca8-9ab0-7ec83394b56a" }
]
